name: Build

on:
  workflow_dispatch:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ['3.8.x', '3.9.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r code-env/python/spec/requirements.txt
          pip install -e .

      - name: Install Dataiku Connector
        id: install-dataiku-connector
        run: |
          python3 --version
          python3 setup.py install
